- name: Create an atomic fedora EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: coinchallenge
    instance_type: t2.micro
    image: ami-8260f9fa
    region: us-west-2
  tasks:
    - name: Find old instances
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          "tag:Application": coin-challenge
      register: old_instances

    - name: Terminate old instances
      ec2:
        state: 'absent'
        instance_ids: 
          - "{{ item.instance_id }}"
        region: "{{ region }}"
      with_items: "{{ old_instances.instances }}"

    - name: Launch instance
      ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        assign_public_ip: True
        vpc_subnet_id: subnet-274a0051
        instance_tags:
          Application: coin-challenge
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- name: Run coin-challenge container on newly launched EC2 instance
  hosts: launched
  remote_user: fedora
  become: True
  become_method: sudo
  become_user: root
  gather_facts: True
  tasks:
    - name: Pull docker image
      docker_image:
        name: "timmyers/coin-challenge-go-ethereum:{{ lookup('env','CIRCLE_SHA1') }}"
    - name: Start docker container
      docker_container:
        name: geth
        image: "timmyers/coin-challenge-go-ethereum:{{ lookup('env','CIRCLE_SHA1') }}"
        entrypoint: /usr/bin/dumb-init
        command: ./build/bin/geth --rpc
        user: go-ethereum
        working_dir: /go-ethereum/repo

    # - docker_service:
    #     definition:
    #       services: 
    #         go-ethereum:
    #           entrypoint: /usr/bin/dumb-init
    #           image: "timmyers/coin-challenge-go-ethereum:{{ lookup('env','CIRCLE_SHA1') }}"
    #           command: ./build/bin/geth
    #           user: go-ethereum
    #           working_dir: /go-ethereum/repo
    #       version: '2'
    #     state: present
    #     project_name: coin-challenge