version: 2
jobs: 
  build:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install ansible-container
          command: pip install ansible-container[docker]
      - run:
          name: Build ansible-container
          command: ansible-container build