version: 2
jobs: 
  build:
    docker:
      - image: timmyers/coin-challenge-ci
    steps:
      - checkout
      - setup_remote_docker
      - run: pwd
      - run: ls -al
      - run:
          name: Build ansible-container
          command: ansible-container build