version: 2
jobs: 
  build:
    machine: 
      image: circleci/classic:201711-01
    steps:
      - checkout
      - run:
          name: Pin python docker version
          command: pip install docker==2.7.0
      - run:
          name: Install ansible-container
          command: |
            pip install ansible-container[docker]
      - run: ansible-container build
      - run: 
          name: ansible-container push (to dockerhub)
          command: |
            sudo rm -rf ~/.docker/config.json
            sudo docker login --username timmyers --password $DOCKERHUB_PW
            ansible-container push --username timmyers --password ${DOCKERHUB_PW} --push-to dockerhub --tag $CIRCLE_SHA1
  deploy:
    docker:
      - image: timmyers/coin-challenge-ci
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "8c:9a:c9:52:86:a4:a3:a9:1d:4d:75:0f:58:7b:1a:83"
      - run:
          name: Run ansible deploy playbook
          command: |
            cd ec2-deployment
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook provision.yml

workflows:
  version: 2
  Build and Deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
