version: 2
jobs: 
  build:
    machine: 
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Update pip, setuptools
          command: |
            sudo add-apt-repository ppa:jonathonf/python-2.7
            sudo apt-get update
            sudo apt-get install python2.7
            # sudo pip install --upgrade python
            # sudo python -m pip install --upgrade pip setuptools python wheel
      - run: 
          name: Install ansible-container
          command: sudo pip install ansible-container[docker]
      - run: docker ps

    
    # docker:
    #   - image: timmyers/coin-challenge-ci
    # steps:
    #   - checkout
    #   - setup_remote_docker
    #   - run:
    #       name: Build ansible-container
    #       command: ansible-container build