version: 2
jobs: 
  build:
    machine: 
      image: circleci/classic:201711-01
    steps:
      - checkout
      - run:
          name: Pin python docker version
          command: pip install docker==2.7.0
      - run:
          name: Instrall ansible-container
          command: pip install ansible-container[docker]
      - run: ansible-container build
      - run: 
          name: ansible-container deploy
          command: |
            sudo rm -rf ~/.docker/config.json
            sudo docker login --username timmyers --password $DOCKERHUB_PW
            ansible-container --engine docker deploy --username timmyers --password ${DOCKERHUB_PW} --push-to dockerhub
      - run: 
          name: View artifacts
          command: |
            ls ansible-deployment
            cat ansible-deployment/coin-challenge.yml