version: 2
jobs: 
  build:
    machine: 
      image: circleci/classic:201711-01
    steps:
      - checkout
      - run:
          name: Pin python docker version
          command: pip install docker==2.7.0
      # - run:
      #     name: Install python deps
      #     command: |
      #       pip install docker==2.7.0
      #       pip install docker-compose
      - run:
          name: Install ansible and ansible-container
          command: |
            pip install ansible-container[docker]
      - run: ansible-container build
      - run: 
          name: ansible-container push
          command: |
            sudo rm -rf ~/.docker/config.json
            sudo docker login --username timmyers --password $DOCKERHUB_PW
            ansible-container push --username timmyers --password ${DOCKERHUB_PW} --push-to dockerhub --tag $CIRCLE_SHA1
  deploy:
    docker:
      - image: timmyers/coin-challenge-ci
    steps:
      - checkout
      - run:
          name: Run ansible deploy playbook
          command: |
            cd ec2-deployment
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook provision.yml

workflows:
  version: 2
  Build and Deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
