version: 2
jobs: 
  build:
    machine: 
      image: circleci/classic:latest
    steps:
      - checkout
      - run: docker ps

    
    # docker:
    #   - image: timmyers/coin-challenge-ci
    # steps:
    #   - checkout
    #   - setup_remote_docker
    #   - run:
    #       name: Build ansible-container
    #       command: ansible-container build